[package]
name = "count-fasta-plots"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
plotters = "0.3.7"
serde = { version = "1.0.210", features = ["derive"] }

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
